knpu_oauth2_client:
    clients:
        uco:
            type: generic
            provider_class: Uco\OAuth2\Client\Provider\Uco
            client_id: '%env(CLIENT_UCO_ID)%'
            client_secret: '%env(CLIENT_UCO_SECRET)%'
            redirect_route: 'connect_uco_check'
