scheb_two_factor:
    google:
        enabled: true
        server_name: locker.aulasoftwarelibre.uco.es
        issuer: Locker
        window: 1
        template: security/2fa_form.html.twig

    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
