vich_uploader:
    db_driver: orm
    mappings:
        codes:
            uri_prefix: /images/codes
            upload_destination: '%kernel.project_dir%/public/images/codes'
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

    metadata:
        type: attribute

